# Generated by Django 3.0.8 on 2020-08-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='author',
        ),
    ]
